package io.github.heberfhlemes.securitystarter.infrastructure.jwt;

import io.github.heberfhlemes.securitystarter.application.ports.TokenProvider;
import io.github.heberfhlemes.securitystarter.properties.JwtProperties;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.JwtException;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;

import javax.crypto.SecretKey;
import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Function;

/**
 * JWT-based implementation of {@link TokenProvider}.
 *
 * <p>
 * This class provides utilities for generating, parsing, and validating JWT tokens.
 * It is designed to be stateless and safe for concurrent use across multiple requests.
 * </p>
 *
 * <p>
 * Tokens generated by this provider use the {@link JwtProperties} configuration for secret keys
 * and expiration times. The "subject" claim is used to represent the principal (usually a username).
 * </p>
 *
 * <p>
 * <strong>Important:</strong> This class does not authenticate credentials. It assumes that
 * the application has already verified user identity and only needs to issue or validate tokens
 * for stateless authentication workflows.
 * </p>
 *
 * <p>
 * Thread-safety: This class is fully thread-safe as it does not mutate any shared state after construction.
 * </p>
 *
 * @author Héber F. H. Lemes
 * @since 0.1.0
 */
public class JwtTokenProvider implements TokenProvider {

    private final JwtProperties properties;
    private final SecretKey signingKey;

    /**
     * Creates a new {@code JwtTokenProvider} with the given properties.
     *
     * @param properties the JWT configuration properties, including secret and expiration
     */
    public JwtTokenProvider(JwtProperties properties) {
        this.properties = properties;
        this.signingKey = Keys.hmacShaKeyFor(
                properties.getSecret().getBytes(StandardCharsets.UTF_8)
        );
    }

    protected SecretKey getSigningKey() {
        return this.signingKey;
    }

    /**
     * Generates a signed JWT token with the specified subject.
     *
     * @param subject the principal or identifier to be stored in the JWT subject claim
     * @return a signed JWT token as a {@link String}
     */
    @Override
    public String generateToken(String subject) {
        Map<String, Object> claims = new HashMap<>();
        return createToken(claims, subject);
    }

    /**
     * Creates a JWT token with custom claims and a subject.
     *
     * @param claims  additional JWT claims to include
     * @param subject the principal or identifier to be stored in the subject claim
     * @return a signed JWT token as a {@link String}
     */
    private String createToken(Map<String, Object> claims, String subject) {
        Instant now = Instant.now();

        return Jwts.builder()
                .claims(claims)
                .subject(subject)
                .issuedAt(Date.from(now))
                .expiration(Date.from(now.plus(properties.getExpiration())))
                .signWith(getSigningKey())
                .compact();
    }

    /**
     * Extracts the subject (principal) from a JWT token.
     *
     * @param token the JWT token
     * @return the subject claim contained in the token
     * @throws JwtException if the token is invalid, malformed, expired, or has an invalid signature
     * @throws IllegalArgumentException if the token is null or empty
     */
    @Override
    public String extractSubject(String token) {
        return extractClaim(token, Claims::getSubject);
    }

    /**
     * Extracts the expiration date from a JWT token.
     *
     * @param token the JWT token
     * @return the token's expiration {@link Date}
     * @throws JwtException if the token is invalid, malformed, expired, or has an invalid signature
     * @throws IllegalArgumentException if the token is null or empty
     */
    public Date extractExpiration(String token) {
        return extractClaim(token, Claims::getExpiration);
    }

    /**
     * Extracts a specific claim from token.
     * @param token JWT token
     * @param claimsResolver a function to resolve claim (like in {@code Claims::getSubject})
     * @return the result of the function {@code apply(claims)} from claimsResolver.
     * @param <T> the type of the result of the function
     * @throws JwtException if the token is invalid, expired, malformed, or has an invalid signature
     * @throws IllegalArgumentException if the token is null or empty
     */
    public <T> T extractClaim(String token, Function<Claims, T> claimsResolver) {
        final Claims claims = extractAllClaims(token);
        return claimsResolver.apply(claims);
    }

    /**
     * Extracts all claims from a JWT token.
     *
     * @param token the JWT token
     * @return the full {@link Claims} payload of the token
     * @throws JwtException if the token is invalid, expired, malformed, or has an invalid signature
     * @throws IllegalArgumentException if the token is null or empty
     */
    protected Claims extractAllClaims(String token) {
        return Jwts.parser()
                .verifyWith(getSigningKey())
                .build()
                .parseSignedClaims(token)
                .getPayload();
    }

    /**
     * Checks whether the token is expired based on the {@code exp} claim.
     * <p>
     * This method assumes the token is already valid and correctly signed.
     * It should not be used as a replacement for {@link #validateToken(String)}.
     *
     * @param token the JWT token
     * @return {@code true} if the token expiration is before the current time
     */
    protected boolean isTokenExpired(String token) {
        return extractExpiration(token).before(new Date());
    }

    /**
     * Validates a JWT token.
     *
     * <p>This method performs full JWT validation, including:
     * <ul>
     *   <li>Signature verification</li>
     *   <li>Token structure validation</li>
     *   <li>Expiration validation</li>
     * </ul>
     *
     * <p>This method does not validate application-specific claims
     * such as subject, roles, or authorities.
     *
     * <p>For callers who need access to token claims or more detailed
     * failure information, use {@link #extractSubject(String)} or
     * {@link #extractClaim(String, Function)} directly.
     *
     * @param token the JWT token
     * @return {@code true} if the token is valid and can be safely used,
     *         {@code false} otherwise
     */
    public boolean validateToken(String token) {
        try {
            extractAllClaims(token);
            return true;
        } catch (JwtException | IllegalArgumentException e) {
            return false;
        }
    }
}
