package io.github.heberfhlemes.securitystarter.infrastructure.jwt;

import io.github.heberfhlemes.securitystarter.application.ports.TokenProvider;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.JwtException;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;

import javax.crypto.SecretKey;
import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Function;

/**
 * JWT-based implementation of {@link TokenProvider}.
 *
 * <p>
 * This class provides utilities for generating, parsing, and validating JWT tokens.
 * It is designed to be stateless and safe for concurrent use across multiple requests.
 * </p>
 *
 * <p>
 * Tokens generated by this provider use the {@link JwtProperties} configuration for secret keys
 * and expiration times. The "subject" claim is used to represent the principal (usually a username).
 * </p>
 *
 * <p>
 * <strong>Important:</strong> This class does not authenticate credentials. It assumes that
 * the application has already verified user identity and only needs to issue or validate tokens
 * for stateless authentication workflows.
 * </p>
 *
 * <p>
 * Thread-safety: This class is fully thread-safe as it does not mutate any shared state after construction.
 * </p>
 *
 * @author Héber F. H. Lemes
 * @since 0.1.0
 */
public class JwtTokenProvider implements TokenProvider {

    private final JwtProperties properties;
    private final SecretKey signingKey;

    /**
     * Creates a new {@code JwtTokenProvider} with the given properties.
     *
     * @param properties the JWT configuration properties, including secret and expiration
     */
    public JwtTokenProvider(JwtProperties properties) {
        this.properties = properties;
        this.signingKey = Keys.hmacShaKeyFor(
                properties.getSecret().getBytes(StandardCharsets.UTF_8)
        );
    }

    private SecretKey getSignKey() {
        return this.signingKey;
    }

    /**
     * Generates a signed JWT token with the specified subject.
     *
     * @param subject the principal or identifier to be stored in the JWT subject claim
     * @return a signed JWT token as a {@link String}
     */
    @Override
    public String generateToken(String subject) {
        Map<String, Object> claims = new HashMap<>();
        return createToken(claims, subject);
    }

    /**
     * Creates a JWT token with custom claims and a subject.
     *
     * @param claims  additional JWT claims to include
     * @param subject the principal or identifier to be stored in the subject claim
     * @return a signed JWT token as a {@link String}
     */
    private String createToken(Map<String, Object> claims, String subject) {
        Instant now = Instant.now();

        return Jwts.builder()
                .claims(claims)
                .subject(subject)
                .issuedAt(Date.from(now))
                .expiration(Date.from(now.plus(properties.getExpiration())))
                .signWith(getSignKey())
                .compact();
    }

    /**
     * Extracts the subject (principal) from a JWT token.
     *
     * @param token the JWT token
     * @return the subject claim contained in the token
     * @throws JwtException if the token is invalid, expired, malformed, or has an invalid signature
     * @throws IllegalArgumentException if the token is null or empty
     */
    @Override
    public String extractSubject(String token) {
        return extractClaim(token, Claims::getSubject);
    }

    /**
     * Extracts the expiration date from a JWT token.
     *
     * @param token the JWT token
     * @return the token's expiration {@link Date}
     * @throws JwtException if the token is invalid, expired, malformed, or has an invalid signature
     * @throws IllegalArgumentException if the token is null or empty
     */
    public Date extractExpiration(String token) {
        return extractClaim(token, Claims::getExpiration);
    }

    /**
     * Extracts a specific claim from token.
     * @param token JWT token
     * @param claimsResolver a function to resolve claim (like in {@code Claims::getSubject})
     * @return the result of the function {@code apply(claims)} from claimsResolver.
     * @param <T> the type of the result of the function
     * @throws JwtException if the token is invalid, expired, malformed, or has an invalid signature
     * @throws IllegalArgumentException if the token is null or empty
     */
    public <T> T extractClaim(String token, Function<Claims, T> claimsResolver) {
        final Claims claims = extractAllClaims(token);
        return claimsResolver.apply(claims);
    }

    /**
     * Extracts all claims from a JWT token.
     *
     * @param token the JWT token
     * @return the full {@link Claims} payload of the token
     * @throws JwtException if the token is invalid, expired, malformed, or has an invalid signature
     * @throws IllegalArgumentException if the token is null or empty
     */
    private Claims extractAllClaims(String token) {
        return Jwts.parser()
                .verifyWith(getSignKey())
                .build()
                .parseSignedClaims(token)
                .getPayload();
    }

    /**
     * Checks if a JWT token is expired.
     *
     * @param token the JWT token
     * @return {@code true} if the token expiration is before the current time
     */
    private boolean isTokenExpired(String token) {
        return extractExpiration(token).before(new Date());
    }

    /**
     * Validates a JWT token against the specified subject.
     *
     * <p>This method returns {@code false} for any invalid token, including:
     * <ul>
     *   <li>Null or empty tokens</li>
     *   <li>Expired tokens</li>
     *   <li>Malformed tokens</li>
     *   <li>Tokens with invalid signatures</li>
     *   <li>Tokens with mismatched subjects</li>
     * </ul>
     *
     * <p>For callers who need to distinguish between different failure modes,
     * use {@link #extractSubject(String)} directly, which will throw specific
     * {@link JwtException} subtypes.
     *
     * @param token   the JWT token
     * @param subject the expected subject claim (principal/username)
     * @return {@code true} if the token is valid and matches the expected subject,
     *         {@code false} otherwise
     */
    public boolean validateToken(String token, String subject) {
        try {
            final String extractedUsername = extractSubject(token);
            return (extractedUsername.equals(subject) && !isTokenExpired(token));
        } catch (JwtException | IllegalArgumentException e) {
            return false;
        }
    }
}
